import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nggaaa - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-white border-b-2 border-black p-8 w-full fixed flex jusitfy-between items-center">
          <div>
            <Link href={"/"} className="logo">
              <h1>NGGAAA</h1>
              <h1>NGGAAA</h1>
              <h1>NGGAAA</h1>
            </Link>
          </div>
          <div className="w-auto ml-auto justify-end">
            <button
              className={
                "shadow-[5px_5px_0px_-1px_rgba(0,0,0,1)] bg-white active:shadow-[3px_3px_0px_-1px_rgba(0,0,0,1)] active:translate-x-1 active:translate-y-1 active:bg-purple-400 py-2 border-black  border-solid border-2 px-4 text-white-500 font-semibold rounded-lg w-auto text-justify transition-all outline-none"
              }
            >
              cv
            </button>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
